//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourtApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRINFP
    {
        public long WRID { get; set; }
        public int PSL { get; set; }
        public string PRSNAME { get; set; }
        public string PRSADDRESS { get; set; }
        public int AREAID { get; set; }
    
        public virtual AREAINF AREAINF { get; set; }
    }
}
