//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourtApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRINF
    {
        public long WRID { get; set; }
        public string WRNUM { get; set; }
        public System.DateTime WRDAT { get; set; }
        public System.DateTime CASEDATE { get; set; }
        public int COURTID { get; set; }
        public string PREGREF { get; set; }
        public string DISPOSE { get; set; }
    
        public virtual COURTINF COURTINF { get; set; }
    }
}
